language: node_js

node_js:
  - '10'
  - '8'

dist: trusty
sudo: false  

matrix:
  fast_finish: true

branches:
  only: 
    - master
    - develop

cache:
  yarn: true
  directories:
    - node_modules

git:
  depth: 1
